# Generated by Django 3.0.6 on 2020-06-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='topping_name',
        ),
    ]
