# Generated by Django 3.0.7 on 2020-08-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description bl bla bla  bla fjsnnnrwj'),
            preserve_default=False,
        ),
    ]
