# Generated by Django 3.0.7 on 2020-09-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0012_auto_20200903_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='overview',
            field=models.CharField(default='best drink ever', max_length=20),
            preserve_default=False,
        ),
    ]
